 sudo: required
 language: generic
 services:
   - docker

  before_install:
    - docker build -t marcindo/docker-react-grider -f Dockerfile.dev .

  script:
    - docker run -e CI=true marcindo/docker-react-grider npm run test -- --coverage
