language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t marcinmarkowskig/docker-react-grider -f Dockerfile.dev .

script:
  - docker run -e CI=true marcinmarkowskig/docker-react-grider npm run test 
